CC = g++
CFLAGS = -g -Wall -DTEST

test_shared.out: smart_ptr_shared.cpp
	$(CC) $(CFLAGS) -o test_shared.out smart_ptr_shared.cpp

test_unique.out: smart_ptr_unique.cpp
	$(CC) $(CFLAGS) -o test_unique.out smart_ptr_unique.cpp
